language: node_js

node_js:
  - 12

install:
  - npm install
  - npm add --dev eslint-config-standard
  - npm add --dev eslint-plugin-node eslint-plugin-react
  - npm add --dev eslint-plugin-promise

script:
  - npm run lint
  - npm run build
  # - npm test
